modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="IEMS"
version="0.6.3"
displayName="Integrated Energy Management System"
authors="等离子工作室 (DLZstudio)"
description='''
综合能源管理系统 - 提供高精度能源管理、Web 监控界面和灵活的电网架构
'''

[[dependencies.IEMS]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.74,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.IEMS]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.IEMS]]
    modId="geckolib"
    type="required"
    versionRange="[4.7.2,)"
    ordering="AFTER"
    side="CLIENT"
